<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita1bc63ee80d795c2c6c12dfc1fb17524
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita1bc63ee80d795c2c6c12dfc1fb17524::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita1bc63ee80d795c2c6c12dfc1fb17524::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita1bc63ee80d795c2c6c12dfc1fb17524::$classMap;

        }, null, ClassLoader::class);
    }
}
